name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Export env
      uses: falti/dotenv-action@v1.0.4
      with:
        path: ./backend/.env
        log-variables: true
        export-variables: true
        keys-case: "bypass"
    - name: Migrate database
      run: |
        sudo apt install sqlite3 -y
        cargo install --version=0.6.3 sqlx-cli --no-default-features --features native-tls,sqlite
        cd backend
        sqlx database create
        : # hack for a sqlx bug that is looking for the db in the root folder
        DB_FILE=$(ls -Art1 ${PWD} | tail -n 1)
        ln -sf ${DB_FILE} ../
        sqlx migrate run
    - uses: actions-rs/cargo@v1
      with:
        command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - name: Export env
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./backend/.env
          log-variables: true
          export-variables: true
          keys-case: "bypass"
      - name: Migrate database
        run: |
          sudo apt install sqlite3 -y
          cargo install --version=0.6.3 sqlx-cli --no-default-features --features native-tls,sqlite
          cd backend
          sqlx database create
          : # hack for a sqlx bug that is looking for the db in the root folder
          DB_FILE=$(ls -Art1 ${PWD} | tail -n 1)
          ln -sf ${DB_FILE} ../
          sqlx migrate run
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings